name: nikcohj
favicon: null
layout_spectrum: 0.16508763586170971
typography_spectrum: 0.6959837595932186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3597733094356954
  lightness: 0.875744829652831
  saturation: 0.5545444844756275
  rhythmicContrast: 0.5053923237137496
purpose: []
